name: Build & Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: List
      run: dotnet Tests.dll +all
      working-directory: /home/runner/work/MemoryLanes/MemoryLanes/Tests/bin/Release/netcoreapp3.1
